spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: riltom
    password: Rilton21
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.formate_sql: true